#' glm.sigModules function
#'
#' This function allows you to find omics modules with significant association to Y (e.g. disease status) using glm. 
#' Dependent packages includes "data.table" and "dplyr". 
#' @param  input.ds  module quantification in the format of a data frame object (with rownames being features and colnames being samples) or the path to the module quantification file generated by ssGSEA2 (gct file) or by WGCNA (txt file)
#' @param  meta.file   meta data prepared in txt file, must contain a column named SampleID and one column named Disease. aim to find significant association between omics modules and Disease. 
#' @param  glm.family   "Guassian" for continuous and unbounded Disease; "binomial" for binary Disease (0/1 or proportions of "successes" and "failures"); "Gamma" or "inverse.gaussian" for continuous non-negative  Disease;  "poisson" for when Disease is counts and when mean is equal to variance;  "quasipoisson" for when Disease is counts
#' @param  glm.p    p-value in glm model to identify significant modules 
#'  
#' @examples
#' metaG.sig.mods <- glm.sigModules(input.ds = "input/path/file", meta.file = "metadata/path/file", glm.family = "binomial")


glm.sigModules <- function(
  input.ds,
  meta.file,
  glm.family = "binomial",
  glm.p = 0.1
){
  
  library(data.table)
  library(dplyr)
  
  if(class(input.ds) == "character"){
    if(grepl("\\.gct$", input.ds)) m  <- parse.gctx(fname=input.ds)@mat %>%  t() %>% as.data.frame() else m <- data.frame(fread(input.ds), row.names=1)
  }else{
    m = input.ds
    feature.abb_df <- cbind.data.frame(feature = rownames(m),
                                       abb = paste("feature",seq(1,nrow(m),1),sep = ""),
                                       stringsAsFactors = F)
    rownames(m) <- sapply(rownames(m), function(x) feature.abb_df$abb[which(feature.abb_df$feature == x)])
    m <- t(m) %>% as.data.frame(stringsAsFactors=F)
  }
  
  
  
  meta_df <- fread(meta.file,data.table = F)
  #meta_df$Disease <- as.factor(meta_df$Disease)
  
  #all(meta_df$SampleID %in% rownames(m.t))
  
  #m.t <- t(m) %>% as.data.frame()
  sig.modules <- vector("character")
  for(md in colnames(m)){
    m.t_sub <- m %>% dplyr::select(all_of(md))
   # if(all(m.t_sub == 0)) next
    dat <- merge(meta_df, m.t_sub, by.x="SampleID", by.y=0,all = T) %>% dplyr::select(-SampleID)
    colnames(dat)[which(colnames(dat) == md)] <- "mod"
    #print(md)
    
    colnames(dat)
    glm.md <- glm(as.formula(paste("Disease ~ ", paste(colnames(dat)[colnames(dat) != "Disease"], collapse = " + "  ), sep = "" )),
                  data = dat, family = glm.family)

    tmp <- summary(glm.md)$coefficients %>% as.data.frame()
    if( !("mod" %in% rownames(tmp)) ) next
    if(tmp$`Pr(>|z|)`[which(rownames(tmp) == "mod")] <= glm.p)  sig.modules <- append(sig.modules, md)
  }
  
  if(all(grepl("^feature", colnames(m)))) sig.modules <- sapply(sig.modules, function(x) feature.abb_df$feature[which(feature.abb_df$abb == x)])
  return(sig.modules)
}

